BEGIN;

DELETE FROM public.product_categories;
DELETE FROM public.categories;

INSERT INTO public.categories (name, slug, description, parent_id, display_order, is_featured)
VALUES
    ('Dog', 'dog', 'Dog food, treats, toys, wellness, travel, and everyday care.', NULL, 10, true),
    ('Cat', 'cat', 'Cat food, litter, toys, furniture, and wellness essentials.', NULL, 20, true),
    ('Bird', 'bird', 'Bird nutrition, habitats, toys, and health products.', NULL, 30, true),
    ('Small Pet', 'small-pet', 'Rabbit, guinea pig, hamster, gerbil, and other small pet essentials.', NULL, 40, true),
    ('Fish & Aquatics', 'fish-aquatics', 'Aquarium food, habitat, filtration, and water care products.', NULL, 50, false),
    ('Reptile', 'reptile', 'Reptile feeding, habitat, lighting, and wellness supplies.', NULL, 60, false),
    ('Farm Animal', 'farm-animal', 'Chicken, horse, goat, sheep, and livestock feed and care.', NULL, 70, true),
    ('Wild Bird', 'wild-bird', 'Wild bird seed, feeders, habitat, and accessories.', NULL, 80, true),
    ('Lawn & Garden', 'lawn-garden', 'Fertilizer, soil, seed, pest control, tools, and seasonal yard care.', NULL, 90, true),
    ('Home', 'home', 'Home heating, household cleaning, and utility essentials.', NULL, 100, false);

INSERT INTO public.categories (name, slug, description, parent_id, display_order, is_featured)
SELECT
    seed.name,
    seed.slug,
    seed.description,
    parent.id,
    seed.display_order,
    seed.is_featured
FROM (
    VALUES
        ('Food', 'dog-food', NULL, 'dog', 10, true),
        ('Treats', 'dog-treats', NULL, 'dog', 20, true),
        ('Health & Wellness', 'dog-health-wellness', NULL, 'dog', 30, false),
        ('Toys', 'dog-toys', NULL, 'dog', 40, true),
        ('Walk & Train', 'dog-walk-train', NULL, 'dog', 50, false),
        ('Beds & Crates', 'dog-beds-crates', NULL, 'dog', 60, false),
        ('Grooming', 'dog-grooming', NULL, 'dog', 70, false),
        ('Waste & Cleanup', 'dog-waste-cleanup', NULL, 'dog', 80, false),

        ('Food', 'cat-food', NULL, 'cat', 10, true),
        ('Treats', 'cat-treats', NULL, 'cat', 20, true),
        ('Litter & Housebreaking', 'cat-litter-housebreaking', NULL, 'cat', 30, true),
        ('Health & Wellness', 'cat-health-wellness', NULL, 'cat', 40, false),
        ('Toys', 'cat-toys', NULL, 'cat', 50, true),
        ('Scratchers & Furniture', 'cat-scratchers-furniture', NULL, 'cat', 60, true),
        ('Carriers & Travel', 'cat-carriers-travel', NULL, 'cat', 70, false),
        ('Grooming', 'cat-grooming', NULL, 'cat', 80, false),

        ('Food', 'bird-food', NULL, 'bird', 10, true),
        ('Habitats', 'bird-habitats', NULL, 'bird', 20, false),
        ('Toys', 'bird-toys', NULL, 'bird', 30, false),
        ('Health & Wellness', 'bird-health-wellness', NULL, 'bird', 40, false),

        ('Food', 'small-pet-food', NULL, 'small-pet', 10, true),
        ('Hay & Forage', 'small-pet-hay-forage', NULL, 'small-pet', 20, true),
        ('Treats & Chews', 'small-pet-treats-chews', NULL, 'small-pet', 30, false),
        ('Bedding & Litter', 'small-pet-bedding-litter', NULL, 'small-pet', 40, false),
        ('Habitats & Accessories', 'small-pet-habitats-accessories', NULL, 'small-pet', 50, false),
        ('Health & Wellness', 'small-pet-health-wellness', NULL, 'small-pet', 60, false),

        ('Food', 'fish-aquatics-food', NULL, 'fish-aquatics', 10, true),
        ('Water Care', 'fish-aquatics-water-care', NULL, 'fish-aquatics', 20, false),
        ('Filtration & Pumps', 'fish-aquatics-filtration-pumps', NULL, 'fish-aquatics', 30, false),
        ('Habitat', 'fish-aquatics-habitat', NULL, 'fish-aquatics', 40, false),
        ('Health & Wellness', 'fish-aquatics-health-wellness', NULL, 'fish-aquatics', 50, false),

        ('Food', 'reptile-food', NULL, 'reptile', 10, true),
        ('Habitat', 'reptile-habitat', NULL, 'reptile', 20, false),
        ('Health & Wellness', 'reptile-health-wellness', NULL, 'reptile', 30, false),

        ('Chicken', 'farm-animal-chicken', NULL, 'farm-animal', 10, true),
        ('Horse', 'farm-animal-horse', NULL, 'farm-animal', 20, true),
        ('Goat & Sheep', 'farm-animal-goat-sheep', NULL, 'farm-animal', 30, false),
        ('Livestock Health', 'farm-animal-livestock-health', NULL, 'farm-animal', 40, false),

        ('Seed & Food', 'wild-bird-seed-food', NULL, 'wild-bird', 10, true),
        ('Feeders', 'wild-bird-feeders', NULL, 'wild-bird', 20, true),
        ('Habitat', 'wild-bird-habitat', NULL, 'wild-bird', 30, false),
        ('Accessories', 'wild-bird-accessories', NULL, 'wild-bird', 40, false),

        ('Fertilizers & Plant Food', 'lawn-garden-fertilizers-plant-food', NULL, 'lawn-garden', 10, true),
        ('Soil, Mulch & Compost', 'lawn-garden-soil-mulch-compost', NULL, 'lawn-garden', 20, true),
        ('Grass Seed & Lawn Repair', 'lawn-garden-grass-seed-lawn-repair', NULL, 'lawn-garden', 30, true),
        ('Pest & Weed Control', 'lawn-garden-pest-weed-control', NULL, 'lawn-garden', 40, true),
        ('Gardening Tools', 'lawn-garden-gardening-tools', NULL, 'lawn-garden', 50, false),
        ('Planters & Seed Starting', 'lawn-garden-planters-seed-starting', NULL, 'lawn-garden', 60, false),
        ('Seasonal & Outdoor Utility', 'lawn-garden-seasonal-outdoor-utility', NULL, 'lawn-garden', 70, false),

        ('Heating & Fuel', 'home-heating-fuel', NULL, 'home', 10, true),
        ('Cleaning & Pest Control', 'home-cleaning-pest-control', NULL, 'home', 20, false),
        ('Storage & Utility', 'home-storage-utility', NULL, 'home', 30, false)
) AS seed(name, slug, description, parent_slug, display_order, is_featured)
JOIN public.categories AS parent
    ON parent.slug = seed.parent_slug;

INSERT INTO public.categories (name, slug, description, parent_id, display_order, is_featured)
SELECT
    seed.name,
    seed.slug,
    seed.description,
    parent.id,
    seed.display_order,
    seed.is_featured
FROM (
    VALUES
        ('Dry Food', 'dog-food-dry-food', NULL, 'dog-food', 10, false),
        ('Wet Food', 'dog-food-wet-food', NULL, 'dog-food', 20, false),
        ('Freeze-Dried & Raw Food', 'dog-food-freeze-dried-raw-food', NULL, 'dog-food', 30, false),
        ('Prescription & Specialty Food', 'dog-food-prescription-specialty-food', NULL, 'dog-food', 40, false),
        ('Biscuits & Crunchy Treats', 'dog-treats-biscuits-crunchy-treats', NULL, 'dog-treats', 10, false),
        ('Jerky & Chews', 'dog-treats-jerky-chews', NULL, 'dog-treats', 20, false),
        ('Training Treats', 'dog-treats-training-treats', NULL, 'dog-treats', 30, false),
        ('Dental Treats', 'dog-treats-dental-treats', NULL, 'dog-treats', 40, false),
        ('Flea & Tick', 'dog-health-wellness-flea-tick', NULL, 'dog-health-wellness', 10, false),
        ('Vitamins & Supplements', 'dog-health-wellness-vitamins-supplements', NULL, 'dog-health-wellness', 20, false),
        ('Digestive & Probiotics', 'dog-health-wellness-digestive-probiotics', NULL, 'dog-health-wellness', 30, false),
        ('Joint Support', 'dog-health-wellness-joint-support', NULL, 'dog-health-wellness', 40, false),
        ('Chew Toys', 'dog-toys-chew-toys', NULL, 'dog-toys', 10, false),
        ('Fetch Toys', 'dog-toys-fetch-toys', NULL, 'dog-toys', 20, false),
        ('Plush & Squeaky Toys', 'dog-toys-plush-squeaky-toys', NULL, 'dog-toys', 30, false),
        ('Interactive Toys', 'dog-toys-interactive-toys', NULL, 'dog-toys', 40, false),
        ('Collars', 'dog-walk-train-collars', NULL, 'dog-walk-train', 10, false),
        ('Harnesses', 'dog-walk-train-harnesses', NULL, 'dog-walk-train', 20, false),
        ('Leashes', 'dog-walk-train-leashes', NULL, 'dog-walk-train', 30, false),
        ('Training & Behavior', 'dog-walk-train-training-behavior', NULL, 'dog-walk-train', 40, false),
        ('Beds', 'dog-beds-crates-beds', NULL, 'dog-beds-crates', 10, false),
        ('Crates & Kennels', 'dog-beds-crates-crates-kennels', NULL, 'dog-beds-crates', 20, false),
        ('Gates & Pens', 'dog-beds-crates-gates-pens', NULL, 'dog-beds-crates', 30, false),
        ('Shampoos & Conditioners', 'dog-grooming-shampoos-conditioners', NULL, 'dog-grooming', 10, false),
        ('Brushes & Combs', 'dog-grooming-brushes-combs', NULL, 'dog-grooming', 20, false),
        ('Nail Care', 'dog-grooming-nail-care', NULL, 'dog-grooming', 30, false),
        ('Waste Bags', 'dog-waste-cleanup-waste-bags', NULL, 'dog-waste-cleanup', 10, false),
        ('Odor & Stain Control', 'dog-waste-cleanup-odor-stain-control', NULL, 'dog-waste-cleanup', 20, false),

        ('Dry Food', 'cat-food-dry-food', NULL, 'cat-food', 10, false),
        ('Wet Food', 'cat-food-wet-food', NULL, 'cat-food', 20, false),
        ('Freeze-Dried & Raw Food', 'cat-food-freeze-dried-raw-food', NULL, 'cat-food', 30, false),
        ('Prescription & Specialty Food', 'cat-food-prescription-specialty-food', NULL, 'cat-food', 40, false),
        ('Crunchy Treats', 'cat-treats-crunchy-treats', NULL, 'cat-treats', 10, false),
        ('Soft Treats', 'cat-treats-soft-treats', NULL, 'cat-treats', 20, false),
        ('Dental Treats', 'cat-treats-dental-treats', NULL, 'cat-treats', 30, false),
        ('Clumping Litter', 'cat-litter-housebreaking-clumping-litter', NULL, 'cat-litter-housebreaking', 10, false),
        ('Natural Litter', 'cat-litter-housebreaking-natural-litter', NULL, 'cat-litter-housebreaking', 20, false),
        ('Litter Boxes & Accessories', 'cat-litter-housebreaking-litter-boxes-accessories', NULL, 'cat-litter-housebreaking', 30, false),
        ('Odor Control', 'cat-litter-housebreaking-odor-control', NULL, 'cat-litter-housebreaking', 40, false),
        ('Flea & Tick', 'cat-health-wellness-flea-tick', NULL, 'cat-health-wellness', 10, false),
        ('Vitamins & Supplements', 'cat-health-wellness-vitamins-supplements', NULL, 'cat-health-wellness', 20, false),
        ('Digestive & Hairball', 'cat-health-wellness-digestive-hairball', NULL, 'cat-health-wellness', 30, false),
        ('Catnip Toys', 'cat-toys-catnip-toys', NULL, 'cat-toys', 10, false),
        ('Interactive Toys', 'cat-toys-interactive-toys', NULL, 'cat-toys', 20, false),
        ('Teasers & Wands', 'cat-toys-teasers-wands', NULL, 'cat-toys', 30, false),
        ('Scratchers', 'cat-scratchers-furniture-scratchers', NULL, 'cat-scratchers-furniture', 10, false),
        ('Trees & Condos', 'cat-scratchers-furniture-trees-condos', NULL, 'cat-scratchers-furniture', 20, false),
        ('Carriers', 'cat-carriers-travel-carriers', NULL, 'cat-carriers-travel', 10, false),
        ('Travel Accessories', 'cat-carriers-travel-travel-accessories', NULL, 'cat-carriers-travel', 20, false),
        ('Brushes & Combs', 'cat-grooming-brushes-combs', NULL, 'cat-grooming', 10, false),
        ('Shampoos & Wipes', 'cat-grooming-shampoos-wipes', NULL, 'cat-grooming', 20, false),

        ('Seed Mixes', 'bird-food-seed-mixes', NULL, 'bird-food', 10, false),
        ('Pellets', 'bird-food-pellets', NULL, 'bird-food', 20, false),
        ('Treats', 'bird-food-treats', NULL, 'bird-food', 30, false),
        ('Cages', 'bird-habitats-cages', NULL, 'bird-habitats', 10, false),
        ('Perches & Stands', 'bird-habitats-perches-stands', NULL, 'bird-habitats', 20, false),
        ('Feeders & Waterers', 'bird-habitats-feeders-waterers', NULL, 'bird-habitats', 30, false),
        ('Foraging Toys', 'bird-toys-foraging-toys', NULL, 'bird-toys', 10, false),
        ('Swings & Chews', 'bird-toys-swings-chews', NULL, 'bird-toys', 20, false),
        ('Vitamins & Supplements', 'bird-health-wellness-vitamins-supplements', NULL, 'bird-health-wellness', 10, false),
        ('Grooming & Beak Care', 'bird-health-wellness-grooming-beak-care', NULL, 'bird-health-wellness', 20, false),

        ('Rabbit Food', 'small-pet-food-rabbit-food', NULL, 'small-pet-food', 10, false),
        ('Guinea Pig Food', 'small-pet-food-guinea-pig-food', NULL, 'small-pet-food', 20, false),
        ('Hamster & Gerbil Food', 'small-pet-food-hamster-gerbil-food', NULL, 'small-pet-food', 30, false),
        ('Timothy Hay', 'small-pet-hay-forage-timothy-hay', NULL, 'small-pet-hay-forage', 10, false),
        ('Alfalfa Hay', 'small-pet-hay-forage-alfalfa-hay', NULL, 'small-pet-hay-forage', 20, false),
        ('Treats', 'small-pet-treats-chews-treats', NULL, 'small-pet-treats-chews', 10, false),
        ('Chews', 'small-pet-treats-chews-chews', NULL, 'small-pet-treats-chews', 20, false),
        ('Paper Bedding', 'small-pet-bedding-litter-paper-bedding', NULL, 'small-pet-bedding-litter', 10, false),
        ('Wood & Natural Bedding', 'small-pet-bedding-litter-wood-natural-bedding', NULL, 'small-pet-bedding-litter', 20, false),
        ('Cages & Hutches', 'small-pet-habitats-accessories-cages-hutches', NULL, 'small-pet-habitats-accessories', 10, false),
        ('Hideouts & Accessories', 'small-pet-habitats-accessories-hideouts-accessories', NULL, 'small-pet-habitats-accessories', 20, false),
        ('Vitamins & Supplements', 'small-pet-health-wellness-vitamins-supplements', NULL, 'small-pet-health-wellness', 10, false),
        ('Grooming', 'small-pet-health-wellness-grooming', NULL, 'small-pet-health-wellness', 20, false),

        ('Fish Food', 'fish-aquatics-food-fish-food', NULL, 'fish-aquatics-food', 10, false),
        ('Aquarium Treats', 'fish-aquatics-food-aquarium-treats', NULL, 'fish-aquatics-food', 20, false),
        ('Conditioners & Treatments', 'fish-aquatics-water-care-conditioners-treatments', NULL, 'fish-aquatics-water-care', 10, false),
        ('Test Kits', 'fish-aquatics-water-care-test-kits', NULL, 'fish-aquatics-water-care', 20, false),
        ('Filters', 'fish-aquatics-filtration-pumps-filters', NULL, 'fish-aquatics-filtration-pumps', 10, false),
        ('Pumps & Aeration', 'fish-aquatics-filtration-pumps-pumps-aeration', NULL, 'fish-aquatics-filtration-pumps', 20, false),
        ('Aquariums', 'fish-aquatics-habitat-aquariums', NULL, 'fish-aquatics-habitat', 10, false),
        ('Decor & Substrate', 'fish-aquatics-habitat-decor-substrate', NULL, 'fish-aquatics-habitat', 20, false),
        ('Disease Treatments', 'fish-aquatics-health-wellness-disease-treatments', NULL, 'fish-aquatics-health-wellness', 10, false),

        ('Feeders', 'reptile-food-feeders', NULL, 'reptile-food', 10, false),
        ('Prepared Food', 'reptile-food-prepared-food', NULL, 'reptile-food', 20, false),
        ('Terrariums', 'reptile-habitat-terrariums', NULL, 'reptile-habitat', 10, false),
        ('Heating & Lighting', 'reptile-habitat-heating-lighting', NULL, 'reptile-habitat', 20, false),
        ('Substrate & Decor', 'reptile-habitat-substrate-decor', NULL, 'reptile-habitat', 30, false),
        ('Supplements', 'reptile-health-wellness-supplements', NULL, 'reptile-health-wellness', 10, false),
        ('Humidity & Thermometers', 'reptile-health-wellness-humidity-thermometers', NULL, 'reptile-health-wellness', 20, false),

        ('Feed', 'farm-animal-chicken-feed', NULL, 'farm-animal-chicken', 10, false),
        ('Treats & Supplements', 'farm-animal-chicken-treats-supplements', NULL, 'farm-animal-chicken', 20, false),
        ('Coop Supplies', 'farm-animal-chicken-coop-supplies', NULL, 'farm-animal-chicken', 30, false),
        ('Feed', 'farm-animal-horse-feed', NULL, 'farm-animal-horse', 10, false),
        ('Treats', 'farm-animal-horse-treats', NULL, 'farm-animal-horse', 20, false),
        ('Supplements', 'farm-animal-horse-supplements', NULL, 'farm-animal-horse', 30, false),
        ('Fly Control', 'farm-animal-horse-fly-control', NULL, 'farm-animal-horse', 40, false),
        ('Feed', 'farm-animal-goat-sheep-feed', NULL, 'farm-animal-goat-sheep', 10, false),
        ('Supplements', 'farm-animal-goat-sheep-supplements', NULL, 'farm-animal-goat-sheep', 20, false),
        ('Dewormers', 'farm-animal-livestock-health-dewormers', NULL, 'farm-animal-livestock-health', 10, false),
        ('Wound Care', 'farm-animal-livestock-health-wound-care', NULL, 'farm-animal-livestock-health', 20, false),
        ('Hoof Care', 'farm-animal-livestock-health-hoof-care', NULL, 'farm-animal-livestock-health', 30, false),

        ('Seed Blends', 'wild-bird-seed-food-seed-blends', NULL, 'wild-bird-seed-food', 10, false),
        ('Suet & Cakes', 'wild-bird-seed-food-suet-cakes', NULL, 'wild-bird-seed-food', 20, false),
        ('Nectar', 'wild-bird-seed-food-nectar', NULL, 'wild-bird-seed-food', 30, false),
        ('Tube Feeders', 'wild-bird-feeders-tube-feeders', NULL, 'wild-bird-feeders', 10, false),
        ('Hopper & Platform Feeders', 'wild-bird-feeders-hopper-platform-feeders', NULL, 'wild-bird-feeders', 20, false),
        ('Suet Feeders', 'wild-bird-feeders-suet-feeders', NULL, 'wild-bird-feeders', 30, false),
        ('Bird Houses', 'wild-bird-habitat-bird-houses', NULL, 'wild-bird-habitat', 10, false),
        ('Bird Baths', 'wild-bird-habitat-bird-baths', NULL, 'wild-bird-habitat', 20, false),
        ('Poles, Baffles & Hangers', 'wild-bird-accessories-poles-baffles-hangers', NULL, 'wild-bird-accessories', 10, false),

        ('Lawn Fertilizer', 'lawn-garden-fertilizers-plant-food-lawn-fertilizer', NULL, 'lawn-garden-fertilizers-plant-food', 10, false),
        ('Garden Fertilizer', 'lawn-garden-fertilizers-plant-food-garden-fertilizer', NULL, 'lawn-garden-fertilizers-plant-food', 20, false),
        ('Plant Food', 'lawn-garden-fertilizers-plant-food-plant-food', NULL, 'lawn-garden-fertilizers-plant-food', 30, false),
        ('Potting Mix', 'lawn-garden-soil-mulch-compost-potting-mix', NULL, 'lawn-garden-soil-mulch-compost', 10, false),
        ('Soil Amendments', 'lawn-garden-soil-mulch-compost-soil-amendments', NULL, 'lawn-garden-soil-mulch-compost', 20, false),
        ('Mulch', 'lawn-garden-soil-mulch-compost-mulch', NULL, 'lawn-garden-soil-mulch-compost', 30, false),
        ('Grass Seed', 'lawn-garden-grass-seed-lawn-repair-grass-seed', NULL, 'lawn-garden-grass-seed-lawn-repair', 10, false),
        ('Lawn Repair', 'lawn-garden-grass-seed-lawn-repair-lawn-repair', NULL, 'lawn-garden-grass-seed-lawn-repair', 20, false),
        ('Insect Control', 'lawn-garden-pest-weed-control-insect-control', NULL, 'lawn-garden-pest-weed-control', 10, false),
        ('Weed Control', 'lawn-garden-pest-weed-control-weed-control', NULL, 'lawn-garden-pest-weed-control', 20, false),
        ('Animal Repellents', 'lawn-garden-pest-weed-control-animal-repellents', NULL, 'lawn-garden-pest-weed-control', 30, false),
        ('Hand Tools', 'lawn-garden-gardening-tools-hand-tools', NULL, 'lawn-garden-gardening-tools', 10, false),
        ('Sprayers & Spreaders', 'lawn-garden-gardening-tools-sprayers-spreaders', NULL, 'lawn-garden-gardening-tools', 20, false),
        ('Watering & Irrigation', 'lawn-garden-gardening-tools-watering-irrigation', NULL, 'lawn-garden-gardening-tools', 30, false),
        ('Planters & Pots', 'lawn-garden-planters-seed-starting-planters-pots', NULL, 'lawn-garden-planters-seed-starting', 10, false),
        ('Seed Starting', 'lawn-garden-planters-seed-starting-seed-starting', NULL, 'lawn-garden-planters-seed-starting', 20, false),
        ('Ice Melt & Snow Care', 'lawn-garden-seasonal-outdoor-utility-ice-melt-snow-care', NULL, 'lawn-garden-seasonal-outdoor-utility', 10, false),
        ('Outdoor Storage & Utility', 'lawn-garden-seasonal-outdoor-utility-outdoor-storage-utility', NULL, 'lawn-garden-seasonal-outdoor-utility', 20, false),

        ('Wood Pellets', 'home-heating-fuel-wood-pellets', NULL, 'home-heating-fuel', 10, false),
        ('Fire Starters', 'home-heating-fuel-fire-starters', NULL, 'home-heating-fuel', 20, false),
        ('Household Cleaners', 'home-cleaning-pest-control-household-cleaners', NULL, 'home-cleaning-pest-control', 10, false),
        ('Indoor Pest Control', 'home-cleaning-pest-control-indoor-pest-control', NULL, 'home-cleaning-pest-control', 20, false),
        ('Trash Bags', 'home-storage-utility-trash-bags', NULL, 'home-storage-utility', 10, false),
        ('Utility Buckets', 'home-storage-utility-utility-buckets', NULL, 'home-storage-utility', 20, false)
) AS seed(name, slug, description, parent_slug, display_order, is_featured)
JOIN public.categories AS parent
    ON parent.slug = seed.parent_slug;

COMMIT;
