from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Workaround: the editable install finder (generated by pip install -e .)
# maintains an explicit mapping of known top-level packages. If 'benchmarks'
# was added after the initial editable install, it won't be found. Patch the
# existing finder to include it until the next pip install -e . regenerates.
try:
    import __editable___baystate_scraper_0_3_0_finder as _finder
    if 'benchmarks' not in _finder.MAPPING:
        _finder.MAPPING['benchmarks'] = str(PROJECT_ROOT / 'benchmarks')
except ImportError:
    pass
